name: "{{ cookiecutter.project_name.lower().replace(' ', '_').replace('-', '_') }}"
channels:
  - conda-forge
dependencies:
  {%- if cookiecutter.require_fenics|lower == "y" %}
  - fenics-dolfin
  {% endif -%}
  {%- if cookiecutter.require_fenicsx|lower == "y" %}
  - fenics-dolfinx
  {% endif -%}
  - jupyter-book
  - python=3.10
